# RakNet Travis

matrix:
  include:
    - os: linux
      env: GCC_VERSION=5 CPP=11 LIBCXX=Off

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - george-edison55/cmake-3.x
      - llvm-toolchain-precise-3.6
    packages:
      - cmake
      - cmake-data
      - gcc-5
      - build-essential
      - g++-5
      - clang-3.6

before_install:
    - sudo add-apt-repository ppa:george-edison55/cmake-3.x --yes
    - sudo apt-get update

install:
    - sudo apt-get install cmake cmake-data
    - sudo apt-get upgrade -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold"

script:
  - export CHECKOUT_PATH=`pwd`;
  - if [ -n "$GCC_VERSION" ]; then export CXX="g++-${GCC_VERSION}" CC="gcc-${GCC_VERSION}"; fi
  - mkdir build && cd build 
  - cmake -DCMAKE_BUILD_TYPE=Debug ..
  - cmake --build . --target AutopatcherServer_PostgreSQL
  - cmake --build . --target AutopatcherClient 
