# RakNet Travis
language: cpp

matrix:
  include:
  # Test gcc-5.0: C++1z
    - env: GCC_VERSION=5 CPP=11 LIBCXX=Off

os: linux

addons:  &gcc5
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - george-edison55/cmake-3.x
      - llvm-toolchain-precise-3.6
    packages:
      - cmake
      - gcc-5
      - build-essential
      - g++-5
      - clang-3.6

script:
  - export CHECKOUT_PATH=`pwd`;
  - if [ -n "$GCC_VERSION" ]; then export CXX="g++-${GCC_VERSION}" CC="gcc-${GCC_VERSION}"; fi
  - mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Debug .. && cmake --build . --target AutopatcherServer_PostgreSQL 
