# RakNet Travis
language: cpp

matrix:
  include:
  # Test gcc-5.0: C++1z
    - env: GCC_VERSION=5 CPP=1z LIBCXX=Off
    -  os: linux

install:
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq build-essential
script:
#  - mkdir build && cd build && cmake -DCOVERALLS=ON -DCMAKE_BUILD_TYPE=Debug .. && cmake --build . && cmake --build . --target coveralls
  - mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX__FLAGS=-std=c++1z CMAKE_SHARED_LINKER_FLAGS=-lstdc++fs .. && cmake --build . --target AutopatcherServer_PostgreSQL 
