# RakNet Travis
language: cpp

matrix:
  include:
  # Test gcc-5.0: C++1z
    - env: GCC_VERSION=5 CPP=11 LIBCXX=Off

os: linux

addons:  &gcc5
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.6
    packages:
      - gcc-5
      - g++-5
      - clang-3.6

install:
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq build-essential gcc-5
script:
  - export CHECKOUT_PATH=`pwd`;
  - if [ -n "$GCC_VERSION" ]; then export CXX="g++-${GCC_VERSION}" CC="gcc-${GCC_VERSION}"; fi
  - mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX__FLAGS=-std=c++1z CMAKE_SHARED_LINKER_FLAGS=-lstdc++fs .. && cmake --build . --target AutopatcherServer_PostgreSQL 
