version: 1.0.{build}
os: Visual Studio 2015
install:
- cmd: "mkdir build \ncd build\ncmake -G \"Visual Studio 14 2015 Win64\" .."
build_script:
- cmd: >-
    cmake --build . --target AutopatcherServer_PostgreSQL

    cmake --build . --target AutopatcherClient
    
    cmake --build . --target AutopatcherClientRestarter
artifacts:
- path: build/Samples/AutopatcherClient
- path: build/Samples/AutopatcherServer
- path: build/Samples/AutopatcherClientRestarter